# Generated by Django 4.2.6 on 2023-10-09 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_userprofile_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
    ]
